export const CONVERSION_MAP: { [key: string]: string[] } = {
    // Document formats
    DOCX: ['PDF', 'HTML', 'JPG', 'ODT', 'PNG', 'RTF', 'TIFF', 'TXT', 'WEBP', 'XML', 'DOCX'],
    PDF: ['DOCX', 'HTML', 'JPG', 'PNG', 'PPTX', 'SVG', 'TXT', 'XLSX', 'PDF/A', 'CSV', 'RTF', 'TIFF', 'WEBP', 'PDF-OCR', 'COMPRESS PDF'],
    HTML: ['PDF', 'DOCX', 'JPG', 'MD', 'ODT', 'PNG', 'TXT', 'XLS', 'XLSX'],
    DOC: ['DOCX', 'HTML', 'JPG', 'ODT', 'PDF', 'PNG', 'RTF', 'TXT', 'XML'],
    DOT: ['JPG', 'PDF'],
    DOTX: ['DOCX', 'JPG', 'ODT', 'PDF', 'RTF', 'XML'],
    ODT: ['DOCX', 'JPG', 'PDF', 'PNG', 'RTF', 'TIFF', 'TXT', 'WEBP', 'XML', 'ODT'],
    PAGES: ['DOCX', 'TXT'],
    RTF: ['HTML', 'JPG', 'PDF', 'PNG', 'TXT'],
    TXT: ['JPG', 'PDF', 'DOCX'],
    LOG: ['DOCX', 'PDF', 'TXT'],
    MD: ['HTML', 'PDF'],
    WPD: ['PDF'],
    XML: ['DOCX', 'ODT', 'RTF', 'XML'],
    // Presentation formats
    PPTX: ['PDF', 'JPG', 'PNG', 'TIFF', 'WEBP', 'PPTX'],
    PPT: ['PDF', 'JPG', 'PNG', 'PPTX', 'TIFF', 'WEBP'],
    KEY: ['PPTX'],
    ODP: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    POTX: ['JPG', 'PDF', 'PNG', 'PPTX', 'TIFF', 'WEBP'],
    PPS: ['JPG', 'PDF', 'PNG', 'PPTX', 'TIFF', 'WEBP'],
    PPSX: ['JPG', 'PDF', 'PNG', 'PPTX', 'TIFF', 'WEBP'],
    // Spreadsheet formats
    XLSX: ['PDF', 'CSV', 'JPG', 'PNG', 'TIFF', 'WEBP', 'XLS'],
    XLS: ['PDF', 'CSV', 'JPG', 'PNG', 'TIFF', 'WEBP', 'XLSX'],
    CSV: ['PDF', 'XLS', 'XLSX'],
    NUMBERS: ['CSV', 'XLSX'],
    ODS: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    XLSB: ['CSV', 'PDF'],
    XLT: ['XLS', 'XLSX'],
    XLTX: ['CSV', 'JPG', 'PDF', 'PNG', 'TIFF', 'WEBP', 'XLS', 'XLSX'],
    // Image formats
    JPG: ['PNG', 'PDF', 'WEBP', 'TIFF', 'GIF', 'SVG', 'JXL', 'TXT', 'JPG', 'PNM'],
    JPEG: ['PNG', 'PDF', 'WEBP', 'TIFF', 'GIF', 'SVG', 'JXL', 'JPG', 'PNM'],
    PNG: ['JPG', 'PDF', 'WEBP', 'TIFF', 'GIF', 'SVG', 'PNM'],
    GIF: ['JPG', 'PDF', 'PNG', 'PNM', 'SVG', 'TIFF', 'WEBP'],
    BMP: ['JPG', 'PDF', 'PNG', 'PNM', 'SVG', 'TIFF', 'WEBP'],
    TIFF: ['JPG', 'PDF', 'PNG', 'PNM', 'SVG', 'WEBP'],
    TIF: ['JPG', 'PNG', 'PNM', 'SVG', 'TIFF', 'WEBP'],
    SVG: ['JPG', 'PDF', 'PNG', 'PNM', 'TIFF', 'WEBP'],
    WEBP: ['JPG', 'PDF', 'PNG', 'GIF', 'PNM', 'SVG', 'TIFF'],
    HEIC: ['JPG', 'JXL', 'PDF', 'PNG', 'PNM', 'SVG', 'TIFF', 'WEBP'],
    HEIF: ['JPG', 'PDF'],
    ICO: ['JPG', 'PDF', 'PNG', 'PNM', 'SVG', 'TIFF', 'WEBP'],
    JFIF: ['PDF'],
    PSD: ['JPG', 'PNG', 'PNM', 'SVG', 'TIFF', 'WEBP'],
    // CAD formats
    DWG: ['JPG', 'PDF', 'PNG', 'SVG', 'TIFF', 'WEBP'],
    DWF: ['JPG', 'PDF', 'PNG', 'SVG', 'TIFF', 'WEBP'],
    DWFX: ['JPG', 'PDF', 'PNG', 'SVG', 'TIFF', 'WEBP'],
    DWGX: ['JPG', 'PNG', 'TIFF', 'WEBP'],
    DXF: ['JPG', 'PDF', 'PNG', 'SVG', 'TIFF', 'WEBP'],
    // Ebook formats
    EPUB: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    MOBI: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    // Email formats
    EML: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    MSG: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    MHTML: ['DOCX', 'ODT'],
    // Other formats
    DJVU: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    EPS: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    ODC: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    ODF: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    ODG: ['PDF'],
    PRN: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    PS: ['JPG', 'PDF', 'PNG', 'TIFF', 'WEBP'],
    PUB: ['JPG', 'PDF', 'PNG', 'TIFF'],
    VSD: ['JPG', 'PDF', 'PNG', 'TIFF'],
    VSDX: ['JPG', 'PDF', 'PNG', 'TIFF'],
    MDI: ['PDF'],
    WEB: ['JPG', 'PNG', 'TXT'],
    // Archive Formats
    ZIP: ['UNZIP']
};
